pasta/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Enable django admin
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('pasta_app.urls')),
)

pasta_app/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout_then_login

from pasta_app.forms import BootstrapAuthForm

urlpatterns = patterns('pasta_app.views',
    url(r'^$', 'home', name='home'),
    url(r'^new/$', 'new_pasta', name='new-pasta'),
    url(r'^accounts/login/$', login, name='login',
        kwargs={'template_name': 'login.html', 'authentication_form': BootstrapAuthForm}),
    url(r'^accounts/logout/$', logout_then_login, name='logout'),

    # These should be last as they matche almost anything
    url(r'^(?P<owner>[^/]+)/(?P<slug>[^/]+)/commit/$', 'do_commit', name='do-commit'),
    url(r'^(?P<owner>[^/]+)/(?P<slug>[^/]+)/(?:(?P<ref>[^/]+)/)?$', 'view_pasta', name='view-pasta'),
)

pasta_app/models.py
import os
import shutil

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import Http404
from dulwich.repo import Repo

from pasta_app.helpers import cached_property

class Repository(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    fork_of = models.ForeignKey('self', null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta(object):
        permissions = (
            ('admin', 'Can admin this repository'),
            ('read', 'Can read from this repository'),
            ('write', 'Can write to this repository'),
        )
        unique_together = ('owner', 'slug')

    @cached_property
    def path(self):
        return os.path.join(settings.REPOSITORY_HOME, self.owner.username, self.slug + '.git')

    @cached_property
    def repo(self):
        return Repo(self.path)

    def fork(self, recipient):
        new_repo = Repository(owner=recipient, name=self.name, fork_of=self)
        shutil.copytree(self.path, new_repo.path)
        new_repo.save()
        return new_repo

    def get_absolute_url(self):
        return reverse('view-pasta', args=[self.owner, self.slug])

    def get_files(self, ref='master'):
        refs = self.repo.get_refs()
        if not refs:  # no commits yet
            return
        elif 'refs/heads/' + ref in refs:
            ref_hash = refs['refs/heads/' + ref]
        elif ref in refs:
            ref_hash = refs[ref]
        elif len(ref) in (20, 40) and ref in self.repo:
            ref_hash = ref
        else:
            raise Http404("The specified ref wasn't found")

        commit = self.repo.commit(ref_hash)
        trees = sorted(self.repo.tree(commit.tree).iteritems(), key=lambda x: x.path)

        for thing in trees:
            if not stat.S_ISREG(thing.mode):  # skip if it's not a file
                pass

            # Get the git blob from the SHA
            blob = self.repo.get_blob(thing.sha)
            yield {
                'path': thing.path,
                'contents': blob.data,
            }

    def commit(self, user, message, files):
        print user

from pasta_app.listeners import *

pasta_git/models.py
import os
import shutil

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Repository(models.Model):
    owner = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    fork_of = models.ForeignKey('self', null=True)

    class Meta(object):
        permissions = (
            ('read', 'Can read from this repository'),
            ('write', 'Can write to this repository'),
        )
        unique_together = ('owner', 'slug')

    @property
    def path(self):
        return os.path.join(settings.REPOSITORY_HOME, self.owner.username, self.slug + '.git')

    def fork(self, recipient):
        new_repo = Repository(owner=recipient, name=self.name, fork_of=self)
        shutil.copytree(self.path, new_repo.path)
        new_repo.save()
        return new_repo

from pasta_git.signals import *

pasta_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from bootstrap.forms import BootstrapModelForm, BootstrapMixin, Fieldset

from pasta_app.models import Repository

class BootstrapAuthForm(BootstrapMixin, AuthenticationForm):
    class Meta:
        layout = (
            Fieldset("Login", "username", "password"),
        )

class NewPastaForm(BootstrapModelForm):
    class Meta:
        model = Repository
        fields = ("name", )

pasta_app/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from guardian.decorators import permission_required_or_403

from pasta_app.models import Repository
from pasta_app.forms import NewPastaForm

@login_required
def home(request):
    return render(request, 'index.html', {
        'new_pasta_form': NewPastaForm(),
        'pastas': Repository.objects.filter(owner=request.user).order_by('-created'),
    })

@login_required
@permission_required_or_403('read', (Repository, 'owner__username', 'owner', 'slug', 'slug'))
def do_commit(request, owner, slug):
    pasta = get_object_or_404(Repository, owner__username=owner, slug=slug)

    # TODO
    to_commit = simplejson.loads(request.raw_post_data)
    pasta.commit(request.user, to_commit['message'], to_commit['files'])
    return HttpResponse('{}', mimetype='application/json')

@login_required
@permission_required_or_403('read', (Repository, 'owner__username', 'owner', 'slug', 'slug'))
def view_pasta(request, owner, slug, ref):
    pasta = get_object_or_404(Repository, owner__username=owner, slug=slug)
    if not ref:
        return HttpResponseRedirect(reverse('view-pasta',
                                    kwargs={'owner': owner, 'slug': slug, 'ref': 'master'}))

    return render(request, 'pasta/view.html', {
        'pasta': pasta,
        'ref': ref,
        'files': list(pasta.get_files(ref)),
    })

@login_required
def new_pasta(request):
    if request.method != 'POST':
        return HttpResponseRedirect(reverse('home'))

    repo = NewPastaForm(request.POST).save(commit=False)
    repo.owner = request.user
    repo.save()
    return HttpResponseRedirect(repo.get_absolute_url())

pasta_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} | Pasta</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/chosen.css" rel="stylesheet">
    <link href="/static/css/pasta.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Pasta</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
            </ul>
          </div><!--/.nav-collapse -->

          {% if request.user.is_authenticated %}
          <ul class="nav pull-right">
            <li><a href="/accounts/logout/">Logout</a></li>
          </ul>
          {% endif %}
          {% block extra-nav %}{% endblock %}
        </div>

      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div> <!-- /container -->

    {% block templates %}{% endblock %}

    <script src="/static/js/json2.js"></script>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/django-csrf.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/chosen.jquery.min.js"></script>
    <script>$(".chzn-select").chosen();</script>

    {% block extra-script %}
    {% endblock %}
  </body>
</html>

pasta_app/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <h2>New pasta</h2>
  <form class="well form-inline" action="/new/" method="POST">
    {% csrf_token %}

    <input id="id_name" type="text" name="name" maxlength="255" placeholder="Name" />
    <button type="submit" class="btn btn-primary">Let's get cooking!</button>
  </form>

  <h2>Your pastas</h2>
  {% if not pastas %}
    <h4>It looks like you don't have any pastas yet. Go and make some!</h4>
  {% endif %}

  {% for pasta in pastas %}
    {% include "pasta/_small_pasta.html" %}
  {% endfor %}
{% endblock %}

pasta_app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<form method="POST" action="{% url login %}" class="form-horizontal">
  {% csrf_token %}
  {{ form }}
  <div class="form-actions">
    <button type="submit" class="btn btn-primary">Login</button>
  </div>
</form>
{% endblock %}

pasta_app/templates/pasta/_repo_actions.html
<div class="pull-right">
  <div class="btn-group pull-left">
    <button class="btn btn-primary" id="add-file" title="Add a file">
      <i class="icon-plus icon-white"></i>
    </button>
  </div>

  <div class="btn-group pull-left">
    <button class="btn btn-danger" id="do-revert" title="Revert your changes">
      <i class="icon-remove icon-white"></i>
    </button>

    <button class="btn btn-success" id="do-commit" title="Commit your changes">
      <i class="icon-ok icon-white"></i>
    </button>
  </div>
</div>

pasta_app/templates/pasta/_small_pasta.html
<ul class="breadcrumb pasta-small">
  <li>
    <i class="icon-user"></i>
    <a href="{{ pasta.owner.get_absolute_url }}">{{ pasta.owner }}</a>
    <span class="divider">/</span>
  </li>
  <li>
    <a href="{{ pasta.get_absolute_url }}">{{ pasta.name }}</a>
  </li>
</ul>

pasta_app/templates/pasta/view.html
{% extends "base.html" %}

{% load guardian_tags pasta_tags %}

{% block title %}{{ pasta.name }}{% endblock %}

{% block extra-nav %}
  {% get_obj_perms request.user for pasta as "pasta_perms" %}
  {% if "write" in pasta_perms %}
    {% include "pasta/_repo_actions.html" %}
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div id="empty-message"></div>

    <div class="span9">
      <div id="pasta-files"></div>
    </div>
    <div class="span3">
    </div>
  </div>
{% endblock %}

{% block extra-script %}
<script src="/static/js/underscore.min.js" type="text/javascript"></script>
<script src="/static/js/backbone.min.js" type="text/javascript"></script>
<script src="/static/js/pasta.js" type="text/javascript"></script>
<script type="text/javascript">
  {% get_obj_perms request.user for pasta as "pasta_perms" %}
  $(function() {
    var pasta = new window.Pasta({{ files|jsonify }});
    var mainView = new window.PastaView({
      collection: pasta,
      permissions: {{ pasta_perms|jsonify }},
      owner: {{ pasta.owner.username|jsonify }},
      slug: {{ pasta.slug|jsonify }}
    });
  });
</script>
{% endblock %}

{% block templates %}
<div id="commit-modal" class="modal hide">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Committing to: {{ pasta.name }}</h3>
  </div>
  <div class="modal-body">
    <p>Commit message:</p>
    <textarea id="commit-message"></textarea>
  </div>
  <div class="modal-footer">
     <a href="#" class="btn" data-dismiss="modal">Close</a>
     <a href="#" id="actually-commit" class="btn btn-success">Commit!</a>
  </div>
</div>
<script type="text/template" id="pasta-file-template">
  <div class="pasta-file">
    <div class="well form-inline">
      <input type="text" class="input-large pasta-file-name"
             placeholder="File name" value="<%= file.get('path') || '' %>" />
      <button class="btn btn-danger remove-file pull-right" title="Remove this file">
        <i class="icon-trash icon-white"></i>
      </button>
    </div>
    <textarea class="pasta-content"><%= file.get('content') || '' %></textarea>
    <hr />
  </div>
</script>
{% endblock %}